# Generated by Django 5.2.9 on 2025-12-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish4hoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='energy',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
