# Generated by Django 5.2.9 on 2025-12-31 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish4hoes', '0002_friend_energy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='hostName',
        ),
        migrations.AddField(
            model_name='friend',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='fish4hoes.event'),
        ),
    ]
